### ISSUE TITLE
The Github link on the footer it is not fully shown

### ISSUE THREAD

**Issue by paschalidi** [dhis2/dhis2.github.io#26]
Hello y'all 👋 

I thought opening my first issue in this great repo you are holding! 

The issue is that on Chrome I see the github icon on the footer a little bit off. 

See screenshot for details.
![image](https://user-images.githubusercontent.com/4181674/78803844-c63fb600-79bf-11ea-8892-4e6d71612b87.png)

Happy to open a PR with this! :D

**Comment by amcgee** [comment]
This should be fixed now
